=== tkhc/projectxml/week4/studentsvb.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
   New Perspectives on XML
   Tutorial 4
   Tutorial case

   Student list schema - Venetian Blind design

   Filename:         studentsvb.xsd
   Supporting Files:
-->

<xsi:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema"
            xmlns="http://example.com/higheredtestprep/students/ns"
            targetNamespace="http://example.com/higheredtestprep/students/ns"
            elementFormDefault="qualified" attributeFormDefault="unqualified">

   <xsi:element name="students">
      <xsi:complexType>
         <xsi:sequence>
            <xsi:element name="student" type="sType" minOccurs="1" maxOccurs="unbounded" />
         </xsi:sequence>
      </xsi:complexType>
   </xsi:element>

   <xsi:complexType name="sType">
      <xsi:group ref="childElements" />
      <xsi:attributeGroup ref="studentAtt" />
   </xsi:complexType>

   <xsi:group name="childElements">
      <xsi:sequence>
         <xsi:element name="lastName" type="xsi:string" />
         <xsi:element name="firstName" type="xsi:string" />
         <xsi:element name="examDate" type="xsi:date" />
         <xsi:element name="pretest" type="pretestComplex" />
         <xsi:element name="score" type="pretestType" minOccurs="0" maxOccurs="unbounded" />
      </xsi:sequence>
   </xsi:group>

   <xsi:attributeGroup name="studentAtt">
      <xsi:attribute name="stuID" type="idType" />
      <xsi:attribute name="courseID" type="courseType" />
   </xsi:attributeGroup>

   <xsi:complexType name="pretestComplex">
      <xsi:simpleContent>
         <xsi:extension base="pretestType">
            <xsi:attribute name="level" type="levelType" use="required" />
         </xsi:extension>
      </xsi:simpleContent>
   </xsi:complexType>

   <xsi:simpleType name="pretestType">
      <xsi:restriction base="xsi:decimal">
         <xsi:minExclusive value="0" />
         <xsi:maxExclusive value="80" />
      </xsi:restriction>
   </xsi:simpleType>

   <xsi:simpleType name="idType">
      <xsi:restriction base="xsi:ID">
         <xsi:pattern value="I\d{4}-\d{3}" />
      </xsi:restriction>
   </xsi:simpleType>

   <xsi:simpleType name="courseType">
      <xsi:restriction base="xsi:string">
         <xsi:pattern value="[A-Z]{4}-\d{3}-\d" />
      </xsi:restriction>
   </xsi:simpleType>

   <xsi:simpleType name="levelType">
      <xsi:restriction base="xsi:string">
         <xsi:enumeration value="L" />
         <xsi:enumeration value="M" />
         <xsi:enumeration value="H" />
      </xsi:restriction>
   </xsi:simpleType>

</xsi:schema>

=== tkhc/projectxml/week4/students.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
   New Perspectives on XML
   Tutorial 4
   Tutorial case

   PSAT mathematics course student list

   Filename:         students.xml
   Supporting Files: studentsfc.xsd, studentsrd.xsd, studentsvb.xsd
-->

<students xmlns:xsi="http://www.w3.org/2001/XMLSchema"
xsi:noNamespaceSchemaLocation="studentsvb.xsd">
   
   <student stuID="I8900-041" courseID="PSAT-080-5">
      <lastName>Garcia</lastName>
      <firstName>Georgianna</firstName>
      <examDate>2017-10-17</examDate>
      <pretest level="M">55</pretest>
      <score>51</score>
   </student>

   <student stuID="I7711-121" courseID="PSAT-080-5">
      <lastName>Smith</lastName>
      <firstName>Ryan</firstName>
      <examDate>2017-10-17</examDate>
      <pretest level="L">25</pretest>
   </student>

   <student stuID="I7012-891" courseID="PSAT-080-5">
      <lastName>Zheng</lastName>
      <firstName>Paddy</firstName>
      <examDate>2017-10-17</examDate>
      <pretest level="H">65</pretest>
   </student>

   <student stuID="I8053-891" courseID="PSAT-080-5">
      <lastName>Steinke</lastName>
      <firstName>Devon</firstName>
      <examDate>2017-10-22</examDate>
      <pretest level="M">51</pretest>
   </student>

   <student stuID="I8154-741" courseID="PSAT-080-5">
      <lastName>Browne</lastName>
      <firstName>Brenda</firstName>
      <examDate>2017-10-22</examDate>
      <pretest level="L">30</pretest>
   </student>

</students>
