=== tkhc/projectxml/week3/students.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
   New Perspectives on XML
   Tutorial 3
   Tutorial Case

   Austin Technical College information technology schema

   Filename:          students.xsd
   Supporting Files:  students.xml

   Author: Terrence Chan 
   Date: 2/11/2021
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:attribute name="stuID" type="siType" />
    <xs:element name="lastName" type="xs:string" />
    <xs:element name="firstName" type="xs:string" />
    <xs:element name="dateOfEnrollment" type="xs:date" />
    <xs:element name="credits" type="creditsType" />
    <xs:element name="comment" type="xs:string" />
    <xs:attribute name="degree" type="degreeType" />

    <xs:simpleType name="siType">
        <xs:restriction base="xs:ID">
            <xs:pattern value="SI\d{3}-\d{3}-\d{2}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="gpa">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="gpaType">
                    <xs:attribute ref="degree" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="creditsType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="gpaType">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0" />
            <xs:maxInclusive value="4" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="degreeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="MP" />
            <xs:enumeration value="WPA" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="lastName" />
                <xs:element ref="firstName" />
                <xs:element ref="dateOfEnrollment" />
                <xs:element ref="credits" />
                <xs:element ref="comment" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="gpa" />
            </xs:sequence>

            <xs:attribute ref="stuID" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="student" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== tkhc/projectxml/week3/students.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="students.css" ?>
<!--
   New Perspectives on XML
   Tutorial 3
   Tutorial Case

   Austin Technical College information technology student list
   
   Filename:         students.xml
   Supporting Files: students.xsd

   Author: Terrence Chan 
   Date: 2/11/2021
-->
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="students.xsd">
   <student stuID="SI890-041-02">
      <lastName>Berstein</lastName>
      <firstName>Cynthia</firstName>
      <dateOfEnrollment>2017-05-22</dateOfEnrollment>
      <credits>12</credits>
      <gpa degree="MP">3.81</gpa>
   </student>

   <student stuID="SI771-121-10">
      <lastName>Boothe</lastName>
      <firstName>Jennifer</firstName>
      <dateOfEnrollment>2017-11-24</dateOfEnrollment>
      <credits>38</credits>
      <comment>Applied for summer studies internship</comment>
      <gpa degree="WPA">3.14</gpa>
   </student>

   <student stuID="SI815-741-03">
      <lastName>Bowen</lastName>
      <firstName>Kristi</firstName>
      <dateOfEnrollment>2017-04-25</dateOfEnrollment>
      <credits>19</credits>
      <gpa degree="MP">3.88</gpa>
   </student>

   <student stuID="SI701-891-05">
      <lastName>Sanchez</lastName>
      <firstName>Rosario</firstName>
      <dateOfEnrollment>2017-08-14</dateOfEnrollment>
      <credits>14</credits>
      <comment>Applied for student tutor</comment>
      <comment>Applied for Women in IT Scholarship</comment>
      <gpa degree="WPA">3.89</gpa>
   </student>

   <student stuID="SI805-891-08">
      <lastName>Russeon</lastName>
      <firstName>Alison</firstName>
      <dateOfEnrollment>2017-09-14</dateOfEnrollment>
      <credits>15</credits>
      <gpa degree="WPA">2.76</gpa>
   </student>
</students>
